In [1]:
import pandas as pd
import numpy as np

In [2]:
#CARREGANDO OS DADOS DA TABELA DE CLIENTES


#LISTA DE NOMES
nomes = [
    "Lucas Araujo", "Gabriel Oliveira", "Pedro Henrique", "Matheus Silva", "Joao Carvalho", "Rafael Santos", "Gustavo Almeida",
    "Felipe Costa", "Bruno Ferreira", "Leonardo Rodrigues", "Carlos Mendes", "Thiago Ribeiro", "Andre Martins", "Daniel Barbosa",
    "Eduardo Lima", "Marcos Souza", "Vinicius Rocha", "Rodrigo Nunes", "Diego Castro", "Caio Moreira", "Henrique Lopes",
    "Fernando Dias", "Guilherme Teixeira", "Arthur Correia", "Samuel Vieira", "Murilo Cardoso", "Igor Monteiro", "Joao Vitor",
    "Enzo Ramos", "Miguel Duarte", "Davi Batista", "Bernardo Freitas", "Nicolas Mendes", "Guilherme Moraes", "Alexandre Reis",
    "Ricardo Fernandes", "Marcelo Tavares", "Wesley Martins", "Victor Hugo", "Luiz Pereira", "Mateus Goncalves", "Otavio Barbosa",
    "Diego Andrade", "Renan Carvalho", "Alan Souza", "Jonathan Melo", "Cristian Lopes", "Nathan Rodrigues", "Emanuel Santos",
    "Yuri Oliveira", "Joao Pedro", "Maria Silva", "Ana Oliveira", "Juliana Santos", "Mariana Costa", "Camila Ferreira",
    "Beatriz Almeida", "Larissa Rodrigues", "Amanda Souza", "Isabela Lima", "Leticia Ribeiro", "Gabriela Martins", "Manuela Carvalho",
    "Luana Mendes", "Rafaela Castro", "Carolina Rocha", "Fernanda Nunes", "Bruna Dias", "Bianca Teixeira", "Aline Correia",
    "Vanessa Vieira", "Natalia Cardoso", "Patricia Monteiro", "Jessica Ramos", "Renata Duarte", "Clara Batista", "Helena Freitas",
    "Laura Moraes", "Valentina Reis", "Sofia Fernandes", "Alice Tavares", "Luiza Pereira", "Yasmin Goncalves", "Eduarda Andrade",
    "Melissa Melo", "Nicole Lopes", "Heloisa Rodrigues", "Isadora Santos", "Cecilia Oliveira", "Elisa Souza", "Agatha Lima",
    "Lorena Ribeiro", "Mirella Martins", "Sarah Carvalho", "Esther Mendes", "Valeria Castro", "Raquel Rocha", "Sabrina Nunes",
    "Tatiane Teixeira"
]

#LISTA DE TELEFONES (GARANTINDO QUE TELEFONES REAIS NÃO SEJAM CRIADOS)
telefone = [f'111222333{i:02d}' for i in range(len(nomes))]

#LISTA DE CPFS (GARANTINDO QUE CPFS REAIS NAO SEJAM CRIADOS)
cpf = [f'000123456{i:02d}' for i in range(len(nomes))]

#LISTA DE ENDEREÇOS
enderecos = [
    "Rua das Amoras", "Rua das Bananas", "Rua das Mangas", "Rua das Laranjas", "Rua dos Abacaxis", "Rua das Uvas", "Rua dos Morangos",
    "Rua das Goiabas", "Rua dos Limões", "Rua das Acerolas", "Rua das Jabuticabas", "Rua das Pitangas", "Rua dos Cajus", "Rua das Melancias",
    "Rua dos Maracujás", "Rua das Framboesas", "Rua dos Mirtilos", "Rua das Cerejas", "Rua dos Pêssegos", "Rua das Peras", "Rua das Maçãs",
    "Rua dos Mamões", "Rua dos Figos", "Rua das Tangerinas", "Rua dos Kiwis", "Rua das Romãs", "Rua dos Abacates", "Rua das Ameixas",
    "Rua das Carambolas", "Rua dos Cocos", "Rua das Graviolas", "Rua dos Tamarindos", "Rua das Pitaias", "Rua dos Physalis", "Rua das Groselhas",
    "Rua dos Duriões", "Rua das Nectarinas", "Rua dos Damascos", "Rua das Lichias", "Rua dos Mangostões", "Rua das Tâmaras", "Rua das Seriguelas",
    "Rua dos Ingás", "Rua das Bacabas", "Rua dos Buritis", "Rua das Pupunhas", "Rua dos Pequis", "Rua das Atemoias", "Rua dos Cambucás",
    "Rua das Grumixamas", "Rua dos Araçás", "Rua dos Jenipapos", "Rua das Mangabas", "Rua dos Muricis", "Rua das Cabeludinhas", "Rua dos Bacuris",
    "Rua das Sapotis", "Rua dos Umbus", "Rua das Pitombas", "Rua dos Oitis", "Rua das Guabirobas", "Rua dos Cajás", "Rua dos Cupuaçus",
    "Rua dos Açaís", "Rua das Castanhas", "Rua dos Pinhas", "Rua das Melões", "Rua das Laranjeiras", "Rua dos Limões-Sicilianos", "Rua das Tangerineiras",
    "Rua dos Pessegueiros", "Rua das Macieiras", "Rua das Pereiras", "Rua dos Morangueiros", "Rua das Cerejeiras", "Rua dos Abacateiros", "Rua das Mangueiras",
    "Rua dos Coqueiros", "Rua das Bananeiras", "Rua das Goiabeiras", "Rua dos Maracujazeiros", "Rua das Aceroleiras", "Rua das Pitangueiras", "Rua dos Cajueiros",
    "Rua das Jabuticabeiras", "Rua das Romãzeiras", "Rua dos Figueirais", "Rua das Ameixeiras", "Rua dos Mamoeiros", "Rua das Caramboleiras", "Rua das Frutas Vermelhas",
    "Rua dos Abacaxis Doces", "Rua das Uvas Roxas", "Rua dos Morangos Silvestres", "Rua das Mangas Rosadas", "Rua dos Limões Verdes", "Rua das Peras Doces", 
    "Rua das Maçãs Verdes", "Rua das Graviolas"
]

#LISTA DE BAIRROS
bairros = [
    "Bairro Leoes", "Bairro Lobos", "Bairro Tigres", "Bairro Ursos", "Bairro Raposas",
    "Bairro Cobras", "Bairro Aguias", "Bairro Falcões", "Bairro Onças",
    "Bairro Elefantes", "Bairro Rinocerontes", "Bairro Gorilas"
]

In [3]:
#CARREGANDO A TABELA DE CLIENTES
dim_cliente = pd.DataFrame(
    {"id_cliente": range(1, len(nomes) + 1),
     "nome": nomes,
     "telefone": telefone,
     "endereco": enderecos,
     "bairro": np.random.choice(bairros, size=len(nomes)),
     "cpf": cpf}
)

dim_cliente

,id_cliente,nome,telefone,endereco,bairro,cpf
0,1,Lucas Araujo,11122233300,Rua das Amoras,Bairro Elefantes,00012345600
1,2,Gabriel Oliveira,11122233301,Rua das Bananas,Bairro Cobras,00012345601
2,3,Pedro Henrique,11122233302,Rua das Mangas,Bairro Rinocerontes,00012345602
3,4,Matheus Silva,11122233303,Rua das Laranjas,Bairro Lobos,00012345603
4,5,Joao Carvalho,11122233304,Rua dos Abacaxis,Bairro Raposas,00012345604
...,...,...,...,...,...,...
94,95,Esther Mendes,11122233394,Rua das Mangas Rosadas,Bairro Falcões,00012345694
95,96,Valeria Castro,11122233395,Rua dos Limões Verdes,Bairro Tigres,00012345695
96,97,Raquel Rocha,11122233396,Rua das Peras Doces,Bairro Raposas,00012345696
97,98,Sabrina Nunes,11122233397,Rua das Maçãs Verdes,Bairro Falcões,00012345697
98,99,Tatiane Teixeira,11122233398,Rua das Graviolas,Bairro Rinocerontes,00012345698

In [4]:
#CARREGANDO OS DADOS DA TABELA VENDEDORES

dim_vendedor = pd.DataFrame(
    {"id_vendedor": [1, 2, 3],
     "nome": ["Pablo", "Allysson", "Ingredi"]}
)

dim_vendedor

   id_vendedor      nome
0            1     Pablo
1            2  Allysson
2            3   Ingredi

In [5]:
#CARREGANDO DADOS DA TABELA CATEGORIA

dim_categoria = pd.DataFrame(
    {"id_categoria": [1, 2, 3, 4],
     "nome": ["Ração", "Acessórios", "Brinquedos", "Banho"],
     "descricao": ["Rações, Petiscos e Alimentos", "Comedouros, Bebedouros e Coleiras", 
                   "Bolinhas, Pelúcias e Demais", "Shampoos, Escovas e Pentes"]
}
)

dim_categoria

   id_categoria        nome                          descricao
0             1       Ração       Rações, Petiscos e Alimentos
1             2  Acessórios  Comedouros, Bebedouros e Coleiras
2             3  Brinquedos        Bolinhas, Pelúcias e Demais
3             4       Banho         Shampoos, Escovas e Pentes

In [6]:
#CARREGANDO DADOS DA TABELA FORMA DE PAGAMENTO

dim_formapagamento = pd.DataFrame(
    {"id_formapag": [1, 2, 3, 4],
     "tipo": ["Dinheiro", "PIX", "Cartão Crédito", "Cartão Débito"]}
)

dim_formapagamento

   id_formapag            tipo
0            1        Dinheiro
1            2             PIX
2            3  Cartão Crédito
3            4   Cartão Débito

In [7]:
#CARREGANDO DADOS DA TABELA PRODUTO (RESOLVI CRIAR SEPARADAMENTE OS PRODUTOS DE CADA CATEGORIA
# PRA FACILITAR A INSERÇÃO DOS DADOS)

id_racoes = [1, 2, 3, 4, 5, 6, 7, 8]
prod_racoes = ["Ração de Combate", "Ração Premium", "Ração Premium Plus", "Ração Premium Especial", 
               "Ração Super Premium", "Bifinhos", "Biscoito", "Sache"]
precocusto_racoes = [40.11, 68.15, 75.24, 95.35, 154.25, 1.54, 14.50, 2.25]

id_acessorios = [9, 10, 11, 12, 13, 14, 15, 16, 17, 18]
prod_acessorios = ["Comedouro/Bebedouro Peq", "Comedouro/Bebedouro Med", "Comedouro/Bebedouro Grd", "Coleira Couro",
                   "Coleira Costura", "Guia", "Peitoral", "Caminha Peq", "Caminha Med", "Caminha Grd"]
precocusto_acessorios = [2.15, 3.35, 5.75, 6.58, 5.42, 8.45, 11.58, 54.15, 65.45, 77.32]

id_brinq = [19, 20, 21, 22, 23, 24, 25, 26]
prod_brinq = ["Brinquedo Hamburguer", "Brinquedo Coxinha", "Bolinha Cravo", "Bola Tenis", "Bola Maciça", 
              "Disco", "Macaco de Pelúcia", "Urso de Pelúcia"]
precocusto_brinq = [4.54, 4.75, 2.25, 7.45, 15.59, 12.45, 12.65, 13.75]

id_banho = [27, 28, 29, 30, 31, 32, 33, 34]
prod_banho = ["Shampoo Clareador", "Shampoo Neutro", "Shampoo Melancia", "Kit Shampoo e Condicionador", 
"Escova de Plástico", "Escova de Aço", "Pente", "Colônia"]
precocusto_banho = [7.99, 7.52, 8.52, 16.45, 10.25, 12.47, 11.25, 9.89]

In [8]:
#PRIMEIRA PARTE DA TABELA DE PRODUTOS (JOGUEI UMA MARGEM ESPECÍFICA SOBRE O PREÇO DE CUSTO
# PRA REPRESENTAR FIELMENTE O PREÇO DE VENDA)

dim_produto = pd.DataFrame(
    {"id_produto": id_racoes,
     "nome": prod_racoes,
     "precoCusto": precocusto_racoes,
     "precoVenda": [preco * 1.45 for preco in precocusto_racoes],
     "quantidadeEstoque": np.random.randint(1, 101, size=len(prod_racoes)),
     "id_categoria": 1}
)


dim_produto

,id_produto,nome,precoCusto,precoVenda,quantidadeEstoque,id_categoria
0,1,Ração de Combate,40.11,58.1595,49,1
1,2,Ração Premium,68.15,98.8175,90,1
2,3,Ração Premium Plus,75.24,109.0980,37,1
3,4,Ração Premium Especial,95.35,138.2575,72,1
4,5,Ração Super Premium,154.25,223.6625,98,1
5,6,Bifinhos,1.54,2.2330,88,1
6,7,Biscoito,14.50,21.0250,22,1
7,8,Sache,2.25,3.2625,32,1

In [9]:
#SEGUNDA PARTE DA TABELA DE PRODUTOS

dim_prod2 = pd.DataFrame(
    {"id_produto": id_acessorios,
     "nome": prod_acessorios,
     "precoCusto": precocusto_acessorios,
     "precoVenda": [preco * 1.75 for preco in precocusto_acessorios],
     "quantidadeEstoque": np.random.randint(1, 101, size=len(prod_acessorios)),
     "id_categoria": 2}
)

dim_produto = pd.concat([dim_produto, dim_prod2], ignore_index=True)

dim_produto

,id_produto,nome,precoCusto,precoVenda,quantidadeEstoque,id_categoria
0,1,Ração de Combate,40.11,58.1595,49,1
1,2,Ração Premium,68.15,98.8175,90,1
2,3,Ração Premium Plus,75.24,109.0980,37,1
3,4,Ração Premium Especial,95.35,138.2575,72,1
4,5,Ração Super Premium,154.25,223.6625,98,1
5,6,Bifinhos,1.54,2.2330,88,1
6,7,Biscoito,14.50,21.0250,22,1
7,8,Sache,2.25,3.2625,32,1
8,9,Comedouro/Bebedouro Peq,2.15,3.7625,23,2
9,10,Comedouro/Bebedouro Med,3.35,5.8625,87,2
10,11,Comedouro/Bebedouro Grd,5.75,10.0625,76,2
11,12,Coleira Couro,6.58,11.5150,74,2
12,13,Coleira Costura,5.42,9.4850,78,2
13,14,Guia,8.45,14.7875,58,2
14,15,Peitoral,11.58,20.2650,25,2
15,16,Caminha Peq,54.15,94.7625,22,2
16,17,Caminha Med,65.45,114.5375,69,2
17,18,Caminha Grd,77.32,135.3100,88,2

In [10]:
#TERCEIRA PARTE DA TABELA DE PRODUTOS

dim_prod3 = pd.DataFrame(
    {"id_produto": id_brinq,
     "nome": prod_brinq,
     "precoCusto": precocusto_brinq,
     "precoVenda": [preco * 1.75 for preco in precocusto_brinq],
     "quantidadeEstoque": np.random.randint(1, 101, size=len(prod_brinq)),
     "id_categoria": 3}
)

dim_produto = pd.concat([dim_produto, dim_prod3], ignore_index=True)

dim_produto

,id_produto,nome,precoCusto,precoVenda,quantidadeEstoque,id_categoria
0,1,Ração de Combate,40.11,58.1595,49,1
1,2,Ração Premium,68.15,98.8175,90,1
2,3,Ração Premium Plus,75.24,109.0980,37,1
3,4,Ração Premium Especial,95.35,138.2575,72,1
4,5,Ração Super Premium,154.25,223.6625,98,1
5,6,Bifinhos,1.54,2.2330,88,1
6,7,Biscoito,14.50,21.0250,22,1
7,8,Sache,2.25,3.2625,32,1
8,9,Comedouro/Bebedouro Peq,2.15,3.7625,23,2
9,10,Comedouro/Bebedouro Med,3.35,5.8625,87,2
10,11,Comedouro/Bebedouro Grd,5.75,10.0625,76,2
11,12,Coleira Couro,6.58,11.5150,74,2
12,13,Coleira Costura,5.42,9.4850,78,2
13,14,Guia,8.45,14.7875,58,2
14,15,Peitoral,11.58,20.2650,25,2
15,16,Caminha Peq,54.15,94.7625,22,2
16,17,Caminha Med,65.45,114.5375,69,2
17,18,Caminha Grd,77.32,135.3100,88,2
18,19,Brinquedo Hamburguer,4.54,7.9450,45,3
19,20,Brinquedo Coxinha,4.75,8.3125,100,3
20,21,Bolinha Cravo,2.25,3.9375,40,3
21,22,Bola Tenis,7.45,13.0375,77,3
22,23,Bola Maciça,15.59,27.2825,100,3
23,24,Disco,12.45,21.7875,21,3
24,25,Macaco de Pelúcia,12.65,22.1375,9,3
25,26,Urso de Pelúcia,13.75,24.0625,63,3

In [11]:
#QUARTA PARTE DA TABELA DE PRODUTO

dim_prod4 = pd.DataFrame(
    {"id_produto": id_banho,
     "nome": prod_banho,
     "precoCusto": precocusto_banho,
     "precoVenda": [preco * 1.75 for preco in precocusto_banho],
     "quantidadeEstoque": np.random.randint(1, 101, size=len(prod_banho)),
     "id_categoria": 4}
)

dim_produto = pd.concat([dim_produto, dim_prod4], ignore_index=True) #VERSÃO FINAL

dim_produto.tail()

,id_produto,nome,precoCusto,precoVenda,quantidadeEstoque,id_categoria
29,30,Kit Shampoo e Condicionador,16.45,28.7875,40,4
30,31,Escova de Plástico,10.25,17.9375,26,4
31,32,Escova de Aço,12.47,21.8225,95,4
32,33,Pente,11.25,19.6875,16,4
33,34,Colônia,9.89,17.3075,98,4

In [12]:
#CARREGANDO DADOS NA TABELA DE DATA

datas = pd.date_range(start="2026-01-01", end="2026-08-31", freq="D")

dias_semana = {
    0: "Segunda",
    1: "Terça",
    2: "Quarta",
    3: "Quinta",
    4: "Sexta",
    5: "Sábado",
    6: "Domingo"
}

meses = {
    1: "Janeiro",
    2: "Fevereiro",
    3: "Março",
    4: "Abril",
    5: "Maio",
    6: "Junho",
    7: "Julho",
    8: "Agosto",
    9: "Setembro"
}

dim_data = pd.DataFrame(
    {"dataCompleta": datas,
     "dia": datas.day,
     "mes": datas.month,
     "nomeMes": datas.month.map(meses),
     "ano": datas.year,
     "diaSemana": datas.dayofweek.map(dias_semana)}
)

dim_data

    dataCompleta  dia  mes  nomeMes   ano diaSemana
0     2026-01-01    1    1  Janeiro  2026    Quinta
1     2026-01-02    2    1  Janeiro  2026     Sexta
2     2026-01-03    3    1  Janeiro  2026    Sábado
3     2026-01-04    4    1  Janeiro  2026   Domingo
4     2026-01-05    5    1  Janeiro  2026   Segunda
..           ...  ...  ...      ...   ...       ...
238   2026-08-27   27    8   Agosto  2026    Quinta
239   2026-08-28   28    8   Agosto  2026     Sexta
240   2026-08-29   29    8   Agosto  2026    Sábado
241   2026-08-30   30    8   Agosto  2026   Domingo
242   2026-08-31   31    8   Agosto  2026   Segunda

[243 rows x 6 columns]

In [13]:
#CARREGANDO DADOS NA TABELA FATO (VENDAS)

#GARANTINDO QUE VENDAS NÃO SEJAM FEITAS AOS DOMINGOS
diasUteis = dim_data[dim_data["diaSemana"] != "Domingo"]["dataCompleta"]

#INSERINDO 5000 TRANSAÇÕES
fato_venda = pd.DataFrame(
    {"id_venda": range(1, 5001),
     "data": np.random.choice(diasUteis, size=5000, replace=True),
     "id_cliente": np.random.choice(dim_cliente["id_cliente"], 5000, replace=True),
     "id_vendedor": np.random.choice(dim_vendedor["id_vendedor"], 5000, replace=True),
     "id_formapag": np.random.choice(dim_formapagamento["id_formapag"], 5000, replace=True),
     "id_produto": np.random.choice(dim_produto["id_produto"], 5000, replace=True),
     "quantidadeVendida": np.random.randint(1, 5, size=5000),
     "desconto": np.round(np.random.uniform(0, 0.05, size=5000), 2)
     }
)

fato_venda

,id_venda,data,id_cliente,id_vendedor,id_formapag,id_produto,quantidadeVendida,desconto
0,1,2026-03-13,39,3,3,17,3,0.04
1,2,2026-06-17,52,2,1,5,4,0.02
2,3,2026-04-14,96,1,3,22,1,0.01
3,4,2026-02-27,8,1,2,3,4,0.05
4,5,2026-03-14,56,2,4,31,1,0.04
...,...,...,...,...,...,...,...,...
4995,4996,2026-03-14,30,1,1,3,4,0.05
4996,4997,2026-02-13,23,3,1,6,2,0.05
4997,4998,2026-02-14,75,2,1,17,4,0.00
4998,4999,2026-07-22,95,2,3,8,2,0.04
4999,5000,2026-08-25,95,2,4,32,1,0.02

In [14]:
#ADICIONANDO A COLUNA DE CUSTO TOTAL (CUSTO POR PRODUTO * QUANTIDADE)

fato_venda["custoTotal"] = (
    fato_venda["id_produto"].map(
        dim_produto.set_index("id_produto")["precoCusto"]
    )
    * fato_venda["quantidadeVendida"]
)

fato_venda

,id_venda,data,id_cliente,id_vendedor,id_formapag,id_produto,quantidadeVendida,desconto,custoTotal
0,1,2026-03-13,39,3,3,17,3,0.04,196.35
1,2,2026-06-17,52,2,1,5,4,0.02,617.00
2,3,2026-04-14,96,1,3,22,1,0.01,7.45
3,4,2026-02-27,8,1,2,3,4,0.05,300.96
4,5,2026-03-14,56,2,4,31,1,0.04,10.25
...,...,...,...,...,...,...,...,...,...
4995,4996,2026-03-14,30,1,1,3,4,0.05,300.96
4996,4997,2026-02-13,23,3,1,6,2,0.05,3.08
4997,4998,2026-02-14,75,2,1,17,4,0.00,261.80
4998,4999,2026-07-22,95,2,3,8,2,0.04,4.50
4999,5000,2026-08-25,95,2,4,32,1,0.02,12.47

In [15]:
#ADICIONANDO A COLUNA DE VALOR DE VENDA BRUTO (PREÇO DE VENDA POR PRODUTO * QUANTIDADE)

fato_venda["valorVendaBruta"] = (
    fato_venda["id_produto"].map(
        dim_produto.set_index("id_produto")["precoVenda"]
    )
    * fato_venda["quantidadeVendida"]
)

fato_venda

,id_venda,data,id_cliente,id_vendedor,id_formapag,id_produto,quantidadeVendida,desconto,custoTotal,valorVendaBruta
0,1,2026-03-13,39,3,3,17,3,0.04,196.35,343.6125
1,2,2026-06-17,52,2,1,5,4,0.02,617.00,894.6500
2,3,2026-04-14,96,1,3,22,1,0.01,7.45,13.0375
3,4,2026-02-27,8,1,2,3,4,0.05,300.96,436.3920
4,5,2026-03-14,56,2,4,31,1,0.04,10.25,17.9375
...,...,...,...,...,...,...,...,...,...,...
4995,4996,2026-03-14,30,1,1,3,4,0.05,300.96,436.3920
4996,4997,2026-02-13,23,3,1,6,2,0.05,3.08,4.4660
4997,4998,2026-02-14,75,2,1,17,4,0.00,261.80,458.1500
4998,4999,2026-07-22,95,2,3,8,2,0.04,4.50,6.5250
4999,5000,2026-08-25,95,2,4,32,1,0.02,12.47,21.8225

In [16]:
#SALVANDO TODAS AS TABELAS EM ARQUIVOS CSV

dim_cliente.to_csv("../data/dim_cliente.csv", index=False)
dim_produto.to_csv("../data/dim_produto.csv", index=False)
dim_vendedor.to_csv("../data/dim_vendedor.csv", index=False)
dim_formapagamento.to_csv("../data/dim_formapagamento.csv", index=False)
dim_data.to_csv("../data/dim_data.csv", index=False)
dim_categoria.to_csv("../data/dim_categoria.csv", index=False)
fato_venda.to_csv("../data/fato_venda.csv", index=False)